window.BUXGALTERIYA_20_PRESET = {
    "companyName":  "Мохларойим Ривож Транс МЧЖ",
    "year":  2019,
    "boshlangichQoldiqlar":  {

                             },
    "operatsiyalar":  [
                          {
                              "id":  "op_1_11",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Миллий валютадаги пул маблағлари",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  65800000,
                              "dt":  "9030",
                              "kt":  "5010",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_12",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Кассадан",
                              "summa":  65800000,
                              "dt":  "5010",
                              "kt":  "5110",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_14",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Мижозлардан",
                              "summa":  27008800,
                              "dt":  "4010",
                              "kt":  "5110",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_16",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Асосий восита",
                              "summa":  12000000,
                              "dt":  "4010",
                              "kt":  "5110",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_19",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Сотиш харажатлари",
                              "mazmuni":  "Маргилон ШЕТК",
                              "summa":  7000000,
                              "dt":  "5110",
                              "kt":  "9410",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_21",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Узоқ муддатли банк кредитлари",
                              "mazmuni":  "Кредит Тани",
                              "summa":  11900000,
                              "dt":  "5110",
                              "kt":  "7810",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_22",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  9950000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_23",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  446000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_24",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "ЕР мулк солиги",
                              "mazmuni":  "Ер солиғи",
                              "summa":  2290000,
                              "dt":  "5110",
                              "kt":  "6415",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_25",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Жамғармалар учун",
                              "summa":  2290000,
                              "dt":  "6415",
                              "kt":  "9430",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_28",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Даромад солиғи (ишчилардан)",
                              "mazmuni":  "Иш хакидан даромад солиги",
                              "summa":  2175500,
                              "dt":  "5110",
                              "kt":  "6411",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_29",
                              "sana":  "2019-01-01",
                              "oy":  1,
                              "hujjat":  "",
                              "mazmuni":  "",
                              "summa":  2175500,
                              "dt":  "6411",
                              "kt":  "4411",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_30",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ягона ижтимоий тўлов",
                              "mazmuni":  "Ягона Ижтимоий тулов",
                              "summa":  2193500,
                              "dt":  "5110",
                              "kt":  "6521",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_31",
                              "sana":  "2019-01-01",
                              "oy":  1,
                              "hujjat":  "",
                              "mazmuni":  "",
                              "summa":  2193500,
                              "dt":  "6521",
                              "kt":  "4521",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_34",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Меҳнат ҳақи бўйича ходим билан ҳисоблашишлар",
                              "mazmuni":  "Олинган иш хаки",
                              "summa":  9168700,
                              "dt":  "5110",
                              "kt":  "6710",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_35",
                              "sana":  "2019-01-01",
                              "oy":  1,
                              "hujjat":  "",
                              "mazmuni":  "",
                              "summa":  9168700,
                              "dt":  "6710",
                              "kt":  "9420",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_37",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  42500000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_39",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "Мижозлар",
                              "summa":  27008800,
                              "dt":  "9030",
                              "kt":  "6310",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_40",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  57547522,
                              "dt":  "6010",
                              "kt":  "1030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_41",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "ЕР мулк солиги",
                              "mazmuni":  "Ер солиғи",
                              "summa":  2290000,
                              "dt":  "6415",
                              "kt":  "9430",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_44",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "304",
                              "summa":  2912500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_45",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "305",
                              "summa":  2912500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_46",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "309",
                              "summa":  2862500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_47",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "316",
                              "summa":  2875000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_48",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "345",
                              "summa":  2937500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_49",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "349",
                              "summa":  2912500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_50",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "351",
                              "summa":  2650000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_51",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "352",
                              "summa":  2875000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_52",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "354",
                              "summa":  2912500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_53",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "356",
                              "summa":  2900000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_54",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "357",
                              "summa":  2900000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_55",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "384",
                              "summa":  2912500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_56",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "449",
                              "summa":  2875000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_57",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "489",
                              "summa":  2675000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_58",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "509",
                              "summa":  2887500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_59",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "510",
                              "summa":  2900000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_60",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "681",
                              "summa":  2875000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_61",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "682",
                              "summa":  2900000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_62",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "683",
                              "summa":  2937500,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_63",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "868",
                              "summa":  2935022,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_71",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ягона солиқ тўлови",
                              "mazmuni":  "ҚҚС",
                              "summa":  3144000,
                              "dt":  "4412",
                              "kt":  "9430",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_80",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Харидорлар ва буюртмачилардан олинган бўнаклар",
                              "mazmuni":  "",
                              "summa":  27008800,
                              "dt":  "6310",
                              "kt":  "4010",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_90",
                              "sana":  "2019-01-31",
                              "oy":  1,
                              "hujjat":  "Ягона солиқ тўлови",
                              "mazmuni":  "ҚҚС",
                              "summa":  3144000,
                              "dt":  "6412",
                              "kt":  "4412",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_105",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Бинолар, иншоотлар ва узатувчи мосламалар",
                              "mazmuni":  "",
                              "summa":  1775180711,
                              "dt":  "0",
                              "kt":  "0120",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_106",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Бино, иншоот ва узатувчи мосламаларнинг эскириши",
                              "mazmuni":  "",
                              "summa":  1184326900,
                              "dt":  "0220",
                              "kt":  "0",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_107",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Харидорлар ва буюртмачилардан олинадиган счётлар",
                              "mazmuni":  "",
                              "summa":  41500000,
                              "dt":  "0",
                              "kt":  "4010",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_108",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Фуқароларнинг жамғариб бориладиган пенсия таъминоти",
                              "mazmuni":  "",
                              "summa":  241132,
                              "dt":  "0",
                              "kt":  "4530",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_112",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Пай ва улушлар",
                              "mazmuni":  "",
                              "summa":  84516711,
                              "dt":  "8330",
                              "kt":  "0",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_113",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Мулкни қайта баҳолаш бўйича тузатишлар",
                              "mazmuni":  "",
                              "summa":  638275000,
                              "dt":  "8510",
                              "kt":  "0",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_114",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Мулкни қайта баҳолаш бўйича тузатишлар",
                              "mazmuni":  "",
                              "summa":  36062000,
                              "dt":  "8510",
                              "kt":  "0",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_118",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Узоқ муддатли банк кредитлари",
                              "mazmuni":  "",
                              "summa":  357000000,
                              "dt":  "7810",
                              "kt":  "0",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_119",
                              "sana":  "2018-12-31",
                              "oy":  1,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "",
                              "summa":  276896300,
                              "dt":  "6010",
                              "kt":  "0",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_1_123",
                              "sana":  "2019-01-01",
                              "oy":  1,
                              "hujjat":  "#N/A",
                              "mazmuni":  "",
                              "summa":  8500000,
                              "dt":  "9430",
                              "kt":  "5820",
                              "izoh":  "Excel import (1-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_10",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Миллий валютадаги пул маблағлари",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  60822900,
                              "dt":  "9030",
                              "kt":  "5010",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_11",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Кассадан",
                              "summa":  60822900,
                              "dt":  "5010",
                              "kt":  "5110",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_12",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Терминал тушум",
                              "summa":  4445000,
                              "dt":  "5710",
                              "kt":  "5110",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_13",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Мижозлардан",
                              "summa":  17520250,
                              "dt":  "4010",
                              "kt":  "5110",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_14",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Йўлдаги пуллар",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  4445000,
                              "dt":  "9030",
                              "kt":  "5710",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_15",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Харидорлар ва буюртмачилардан олинадиган счётлар",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  17520250,
                              "dt":  "9030",
                              "kt":  "4010",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_16",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Сифат Тараккиёт",
                              "summa":  4500000,
                              "dt":  "5820",
                              "kt":  "5110",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_20",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Терминал ижараси",
                              "summa":  30000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_22",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Электр энергияси учун",
                              "summa":  1002000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_25",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  10400000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_26",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Сотиш харажатлари",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  202730,
                              "dt":  "5110",
                              "kt":  "9410",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_27",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Мулк солиғи",
                              "summa":  110890,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_28",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Мақсадли давлат жамғармаларига тўловлар",
                              "mazmuni":  "Фойда солиги",
                              "summa":  600000,
                              "dt":  "5110",
                              "kt":  "6520",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_29",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ягона солиқ тўлови",
                              "mazmuni":  "ҚҚС",
                              "summa":  2019710,
                              "dt":  "5110",
                              "kt":  "6412",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_31",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ягона ижтимоий тўлов",
                              "mazmuni":  "Ягона ижтимоий тулов",
                              "summa":  1574450,
                              "dt":  "5110",
                              "kt":  "6521",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_34",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  41000000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_37",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  51242246,
                              "dt":  "6010",
                              "kt":  "1030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_39",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "304",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_40",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "305",
                              "summa":  2622600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_41",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "309",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_42",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "316",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_43",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "345",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_44",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "349",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_45",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "351",
                              "summa":  2734200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_46",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "352",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_47",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "354",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_48",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "356",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_49",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "357",
                              "summa":  2399400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_50",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "384",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_51",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "449",
                              "summa":  2455200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_52",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "489",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_53",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "509",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_54",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "510",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_55",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "681",
                              "summa":  2455200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_56",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "682",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_57",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "683",
                              "summa":  2343600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_58",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "868",
                              "summa":  2584646,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_62",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Маъмурий харажатлар",
                              "mazmuni":  "Ягона ижтимоий тулов",
                              "summa":  1703150,
                              "dt":  "6521",
                              "kt":  "9420",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_65",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "ҚҚС",
                              "summa":  3770600,
                              "dt":  "6412",
                              "kt":  "9430",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_3_66",
                              "sana":  "2019-03-31",
                              "oy":  3,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Фойда солиги",
                              "summa":  220000,
                              "dt":  "6520",
                              "kt":  "9430",
                              "izoh":  "Excel import (3-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_10",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Миллий валютадаги пул маблағлари",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  75947300,
                              "dt":  "9030",
                              "kt":  "5010",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_11",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Кассадан",
                              "summa":  75947300,
                              "dt":  "5010",
                              "kt":  "5110",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_12",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Терминал тушум",
                              "summa":  4434500,
                              "dt":  "5710",
                              "kt":  "5110",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_13",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Мижозлардан",
                              "summa":  19550250,
                              "dt":  "4010",
                              "kt":  "5110",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_14",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Йўлдаги пуллар",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  4434500,
                              "dt":  "9030",
                              "kt":  "5710",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_15",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Харидорлар ва буюртмачилардан олинадиган счётлар",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  19550250,
                              "dt":  "9030",
                              "kt":  "4010",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_16",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Хусанбой Гранд сервис",
                              "summa":  16420000,
                              "dt":  "5820",
                              "kt":  "5110",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_20",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Терминал ижараси",
                              "summa":  30000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_22",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Электр энергияси учун",
                              "summa":  852000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_25",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  12558000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_26",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Сотиш харажатлари",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  405460,
                              "dt":  "5110",
                              "kt":  "9410",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_28",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Мақсадли давлат жамғармаларига тўловлар",
                              "mazmuni":  "Фойда солиги",
                              "summa":  220000,
                              "dt":  "5110",
                              "kt":  "6520",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_29",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ягона солиқ тўлови",
                              "mazmuni":  "ҚҚС",
                              "summa":  2237600,
                              "dt":  "5110",
                              "kt":  "6412",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_30",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Даромад солиғи (ишчилардан)",
                              "mazmuni":  "Иш хакидан даромад солиги",
                              "summa":  1826000,
                              "dt":  "5110",
                              "kt":  "6411",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_31",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ягона ижтимоий тўлов",
                              "mazmuni":  "Ягона ижтимоий тулов",
                              "summa":  1566200,
                              "dt":  "5110",
                              "kt":  "6521",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_34",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  37000000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_37",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  52032404,
                              "dt":  "6010",
                              "kt":  "1030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_39",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "304",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_40",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "305",
                              "summa":  2622600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_41",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "309",
                              "summa":  2734200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_42",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "316",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_43",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "345",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_44",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "349",
                              "summa":  2734200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_45",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "351",
                              "summa":  2622600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_46",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "352",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_47",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "354",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_48",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "356",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_49",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "357",
                              "summa":  2678400,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_50",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "384",
                              "summa":  2622600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_51",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "449",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_52",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "489",
                              "summa":  2734200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_53",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "509",
                              "summa":  2622600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_54",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "510",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_55",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "681",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_56",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "682",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_57",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "683",
                              "summa":  2566800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_58",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "868",
                              "summa":  2482004,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_65",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "ҚҚС",
                              "summa":  4796950,
                              "dt":  "6412",
                              "kt":  "9430",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_66",
                              "sana":  "2019-04-30",
                              "oy":  4,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Фойда солиги",
                              "summa":  260000,
                              "dt":  "6520",
                              "kt":  "9430",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_4_75",
                              "sana":  "2019-04-01",
                              "oy":  4,
                              "hujjat":  "",
                              "mazmuni":  "",
                              "summa":  4850000,
                              "dt":  "5820",
                              "kt":  "6610",
                              "izoh":  "Excel import (4-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_10",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Миллий валютадаги пул маблағлари",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  58455900,
                              "dt":  "9030",
                              "kt":  "5010",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_11",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Кассадан",
                              "summa":  58455900,
                              "dt":  "5010",
                              "kt":  "5110",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_12",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Терминал тушум",
                              "summa":  3410000,
                              "dt":  "5710",
                              "kt":  "5110",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_13",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ҳисоб-китоб счёти",
                              "mazmuni":  "Мижозлардан",
                              "summa":  15500000,
                              "dt":  "4010",
                              "kt":  "5110",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_14",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Йўлдаги пуллар",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  3410000,
                              "dt":  "9030",
                              "kt":  "5710",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_15",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Харидорлар ва буюртмачилардан олинадиган счётлар",
                              "mazmuni":  "Транспорт хизмати тушуми",
                              "summa":  15500000,
                              "dt":  "9030",
                              "kt":  "4010",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_20",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Терминал ижараси",
                              "summa":  30000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_22",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Электр энергияси учун",
                              "summa":  702000,
                              "dt":  "5110",
                              "kt":  "9430",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_25",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  11675000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_26",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Сотиш харажатлари",
                              "mazmuni":  "Транспорт агентлиги",
                              "summa":  405460,
                              "dt":  "5110",
                              "kt":  "9410",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_28",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Мақсадли давлат жамғармаларига тўловлар",
                              "mazmuni":  "Фойда солиги",
                              "summa":  260000,
                              "dt":  "5110",
                              "kt":  "6520",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_30",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Даромад солиғи (ишчилардан)",
                              "mazmuni":  "Иш хакидан даромад солиги",
                              "summa":  1763000,
                              "dt":  "5110",
                              "kt":  "6411",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_31",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ягона ижтимоий тўлов",
                              "mazmuni":  "Ягона ижтимоий тулов",
                              "summa":  1778000,
                              "dt":  "5110",
                              "kt":  "6521",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_34",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Мол етказиб берувчилар ва пудратчиларга тўланадиган счётлар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  37000000,
                              "dt":  "5110",
                              "kt":  "6010",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_37",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ёқилғилар",
                              "mazmuni":  "OOO MIG OIL METAN",
                              "summa":  48329664,
                              "dt":  "6010",
                              "kt":  "1030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_39",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "304",
                              "summa":  2343600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_40",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "305",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_41",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "309",
                              "summa":  2287800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_42",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "316",
                              "summa":  2176200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_43",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "345",
                              "summa":  2232000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_44",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "349",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_45",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "351",
                              "summa":  2343600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_46",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "352",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_47",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "354",
                              "summa":  2455200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_48",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "356",
                              "summa":  2294664,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_49",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "357",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_50",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "384",
                              "summa":  2343600,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_51",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "449",
                              "summa":  2287800,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_52",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "489",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_53",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "509",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_54",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "510",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_55",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "681",
                              "summa":  2455200,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_56",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "682",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_57",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "683",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_58",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Ишлар бажариш ва хизматлар кўрсатишдан даромадлар",
                              "mazmuni":  "868",
                              "summa":  2511000,
                              "dt":  "1030",
                              "kt":  "9030",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_65",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "ҚҚС",
                              "summa":  3782000,
                              "dt":  "6412",
                              "kt":  "9430",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          },
                          {
                              "id":  "op_5_66",
                              "sana":  "2019-05-01",
                              "oy":  5,
                              "hujjat":  "Бошқа операцион харажатлар",
                              "mazmuni":  "Фойда солиги",
                              "summa":  350000,
                              "dt":  "6520",
                              "kt":  "9430",
                              "izoh":  "Excel import (5-oy)",
                              "isManual":  true
                          }
                      ]
};